### ISSUE TITLE
Build system does not use devkitARM environment variable

### ISSUE THREAD

**Issue by nicholatian** [KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade#22]
```
~/src/em-battle-engine  master ✗                                                        8d ⚑ ◒  ⍉
€ scripts/build
Traceback (most recent call last):
  File "scripts/build", line 86, in <module>
    main()
  File "scripts/build", line 82, in main
    linked = link(itertools.chain.from_iterable(objects))
  File "scripts/build", line 53, in link
    cmd = [LD] + LDFLAGS + ['-o', linked] + list(objects)
  File "scripts/build", line 40, in process_assembly
    run_command(cmd)
  File "scripts/build", line 25, in run_command
    subprocess.check_output(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'C://devkitPro//devkitARM//bin//arm-none-eabi-as'

~/src/em-battle-engine  master ✗                                                        8d ⚑ ◒  ⍉
€ echo $DEVKITARM
/opt/devkitpro/devkitARM
```

It should check if `$DEVKITARM` is set in people’s environments and use it if available.

**Comment by KDSKardabox** [comment]
For the time being assign the PATH manually as given in the updated instructions in Readme.md

**Comment by KDSKardabox** [comment]
Fixed.
